name: merge
on: 
   push:
   workflow_dispatch:
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}  #get_personnel_access_token https://github.com/settings/tokens
      - name: Merge upstream
        run: |
          export repo=RDP_Linux 
          sleep 2
          git config --global user.name 'jha-oajka'
          sleep 2
          git config --global user.email 'jha-oajka@users.noreply.github.com'
          sleep 2
          git pull --unshallow  
          sleep 2
          git remote add upstream https://github.com/amitstudydude/$repo.git
          sleep 2
          git fetch upstream
          sleep 2         
          git checkout main
          sleep 2
          git merge --no-edit upstream/main
          sleep 2 
          git push origin main
          sleep 2
          cd .github/workflows && sleep 2
          sleep 2
          sudo unlink /etc/localtime  && sleep 2
          sleep 2
          sudo ln -s /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
          sleep 2
          date > .md && sleep 2
          sleep 2
          git config --global user.name 'jha-oajka'
          sleep 2
          git config --global user.email 'jha-oajka@users.noreply.github.com'
          sleep 2
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          sleep 2
          git checkout "${GITHUB_REF:11}"
          sleep 2
          git add -A
          sleep 2
          git commit -am "Automated report"
          sleep 2
          git push origin main
          sleep 2
          
