
name: main
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'Code'
        required: true
        default:
  
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:     
    - name: Start Chrome Remote Desktop
      run: |
           wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
           sudo apt install --assume-yes --fix-broken ./*.deb && rm *.deb
           sudo useradd -m user && sudo adduser user sudo && echo 'user:user' | sudo passwd user
           sudo usermod -a -G sudo,adm user
           ${{ github.event.inputs.auth }} -pin=123456
           sudo apt install firefox xfce4 -y
           sudo systemctl restart chrome-remote-desktop@$USER
           echo "bash bash.sh" > bash.sh && bash bash.sh 
