#!/bin/bash
ID="qwiklabs-gcp-03-c956f8b6f212"
gcloud compute instances create instance \
--project=$ID \
--zone=asia-south2-a \
--machine-type=custom-6-39936 \
--image=projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20220420 \
--boot-disk-size=500 \
--boot-disk-type=projects/$ID/zones/asia-south2-a/diskTypes/pd-ssd 
gcloud compute ssh --zone "asia-south2-a" "instance"  --project "$ID"
