#!/bin/expect -f

spawn pagekite.py 8080 jhaji.pagekite.me
match_max 100000
expect -exact "\r
\[0m\r\[H\[J\[1m>>> Creating kite: jhaji.pagekite.me                          \[CTRL+C = Cancel\]\r
\r
\[0m\r    Welcome to PageKite!\r
    \r
    Please answer a few quick questions to\r
    create your first kite.\r
    \r
    By continuing, you agree to play nice\r
    and abide by the Terms of Service at:\r
    - https://pagekite.net/humans.txt\r
\r
\[0m\r => Use the PageKite.net service? \[Y/n\] "
send -- "y\r"
expect -exact "y\r
\[H\[J\[1m>>> Creating kite: jhaji.pagekite.me                          \[CTRL+C = Cancel\]\r
\r
\[0m\r    We need to be able to contact you\r
    now and then with news about the\r
    service and your account.\r
    \r
    Your details will be kept private.\r
\r
\[0m\r => What is your e-mail address? "
send -- "gpw97v95c@mozmail.com"
expect -exact "gpw97v95c@mozmail.com"
send -- "\r"
expect -exact "\r
\[H\[J\[1m>>> Creating kite: jhaji.pagekite.me                          \[CTRL+C = Cancel\]\r
\r
\[0m\r*** Signing up ...\r
\r
\[0m\r\[H\[J\[1m>>> Creating kite: jhaji.pagekite.me                          \[CTRL+C = Cancel\]\r
\r
\[0m\r*** Signup failed!\r
*** \r
*** You already have an account. Log in to continue.\r
\r
\[0m\r    By logging on to PageKite.net,\r
    you will be able to use this kite\r
    with your pre-existing account.\r
\r
\[0m\r    Please log on ...\r
 => Password: "
send -- "24ebe38z\r"
expect -exact "\r
\[H\[J\[1m>>> Creating kite: jhaji.pagekite.me                          \[CTRL+C = Cancel\]\r
\r
\[0m\r*** Logging on to your account ...\r
\r
\[0m\r\[H\[J\[1m>>> Creating kite: jhaji.pagekite.me                          \[CTRL+C = Cancel\]\r
\r
\[0m\r*** Logging on to your account ... done.\r
*** Creating your kite ...\r
\r
\[0m\r\[H\[J\[1m>>> Creating kite: jhaji.pagekite.me                          \[CTRL+C = Cancel\]\r
\r
\[0m\r*** Success!\r
\r
\[0m\r\r
\[0m\r => Save settings to /root/.pagekite.rc? \[Y/n\] "
send -- "y\r"
expect -exact "y\r
\r
\[0m\r    Settings saved to: /root/.pagekite.rc\r
\r
\r << pagekite.py \[startup\]  \[0mStarting up...                                      \r\[0m\r>>> \[32;1mHello! This is pagekite.py v1.5.2.201011.\[0m                   \[CTRL+C = Stop\]\r
\r << pagekite.py \[startup\]  \[0mStarting up...                                      \r\[0m\r << pagekite.py \[startup\]  \[0mCollecting entropy for a secure secret...           \r\[0m\r << pagekite.py \[startup\]  \[0mStarting up...                                      \r\[0m\r << pagekite.py \[connect\]  \[33;1mFront-end connect: 45.33.98.215:443                 \r\[0m\r    \[0mConnecting to front-end relay 45.33.98.215:443 ...\[0m                         \r
\r << pagekite.py \[connect\]  \[33;1mFront-end connect: 45.33.98.215:443                 \r\[0m\r    \[0m - Relay supports 10 protocols on 23 public ports.\[0m                         \r
\r << pagekite.py \[connect\]  \[33;1mFront-end connect: 45.33.98.215:443                 \r\[0m\r    \[0m - Raw TCP/IP (HTTP proxied) kites are available.\[0m                          \r
\r << pagekite.py \[connect\]  \[33;1mFront-end connect: 45.33.98.215:443                 \r\[0m\r    \[0m - To enable more logging, add option: --logfile=/path/to/logfile\[0m          \r
\r << pagekite.py \[connect\]  \[33;1mFront-end connect: 45.33.98.215:443                 \r\[0m\r    \[35;1mAbuse/DDOS protection: Relaying traffic for up to 5 clients per 10800s.\[0m    \r
\r << pagekite.py \[connect\]  \[33;1mFront-end connect: 45.33.98.215:443                 \r\[0m\r    \[35;1mQuota: You have 29 days, 4.0 tunnels left.\[0m                                 \r
\r << pagekite.py \[connect\]  \[33;1mFront-end connect: 45.33.98.215:443                 \r\[0m\r << pagekite.py \[dyndns\]   \[33;1mUpdating DNS for 5555-jha.pagekite.me...            \r\[0m"

