#!/bin/expect -f

set timeout -1
spawn pagekite.py $port $domain
match_max 100000
expect "\r
\[0m\r\[H\[J\[1m>>> Creating kite: $domain                       \[CTRL+C = Cancel\]\r
\r
\[0m\r    $domain is a sub-domain.\r
    \r
    NOTE: This process will fail if you\r
    have not already registered the parent\r
    domain, $parent.\r
\r
\[0m\r => Use this name? \[Y/n\] "
send -- "y\r"
expect -exact "y\r
\[H\[J\[1m>>> Creating kite: $domain                       \[CTRL+C = Cancel\]\r
\r
\[0m\r*** Creating your kite ...\r
\r
\[0m\r\[H\[J\[1m>>> Creating kite: $domain                       \[CTRL+C = Cancel\]\r
\r
\[0m\r*** Success!\r
\r
\[0m\r\r
\[0m\r => Save settings to /root/.pagekite.rc? \[Y/n\] "
send -- "y\r"
expect eof
