name: rerun
on:
  workflow_run:
    workflows: [merge]
    types: [completed]
  workflow_dispatch:
jobs:
  trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}  #get_personnel_access_token https://github.com/settings/tokens
      - name: Merge upstream
        run: |
          export repo=runner
          sleep 2
          git config --global user.name 'jha-oajka'
          sleep 2
          git config --global user.email 'jha-oajka@users.noreply.github.com'
          sleep 2
          git pull --unshallow  
          sleep 2
          git remote add upstream https://github.com/amitstudydude/$repo.git
          sleep 2
          git fetch upstream
          sleep 2         
          git checkout main
          sleep 2
          git merge --no-edit upstream/main
          sleep 2 
          git push origin main
          sleep 2
          cd .github/workflows && sleep 2
          sleep 2
          sudo unlink /etc/localtime  && sleep 2
          sleep 2
          sudo ln -s /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
          sleep 2
          date >> .txt && sleep 2
          sleep 2
          git config --global user.name 'jha-oajka'
          sleep 2
          git config --global user.email 'jha-oajka@users.noreply.github.com'
          sleep 2
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          sleep 2
          git checkout "${GITHUB_REF:11}"
          sleep 2
          git add -A
          sleep 2
          git commit -am "Automated report"
          sleep 2
          git push origin main
          sleep 2
          #curl \
          ##-X POST \
          ###-H "Accept: application/vnd.github.v3+json" \
          ### -H "Authorization: token $token" \
          ####https://api.github.com/repos/amitstudydude/runner/merge-upstream \
          ### -d '{"branch":"main"}'
