#!/bin/bash
docker pull jlesage/firefox
docker run -d --name temp_firefox -p 5800:5800 jlesage/firefox
read -p "Access the Firefox container at http://localhost:5800. Log in and configure Firefox. Press Enter once done."
docker commit temp_firefox firefox
docker stop temp_firefox
docker rm temp_firefox
docker tag firefox amitstudydude/firefox:latest
docker push amitstudydude/firefox:latest